PDZH/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
from django.views.static import serve
from . import settings


urlpatterns = [

    # 用户账户
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('projects/', include('projects.urls')),
    path('captcha/', include('captcha.urls')),  # 增加验证码路由
    path('notifications/', include('notifications.urls', namespace='notifications')),  # 增加消息库链接
    url('media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),

    ]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views

#  定义项目和开票url
app_name = 'projects'

urlpatterns = [

    path('index/', views.index, name='index'),
    # 项目管理
    path('explist/', views.explist, name='pro_list'),
    path('add_exp/', views.add_exp, name='add_exp'),
    path('pro/<int:pro_id>/', views.pro_detail),
    path('del_pro/<int:pro_id>/', views.pro_del),

    # 开票回款
    path('invoice_payment/', views.invoice_payment, name='invoice_list'),
    path('invoice/<int:inv_id>/', views.invoice_detail),
    path('del_inv/<int:inv_id>/', views.inv_del),

    # 开票申请记录
    path('applylist/', views.applylist, name='apply_list'),   # 定义开票申请列表链接
    path('apply/<int:apply_id>/', views.apply_detail, name='apply_detail'),
    path('del_apply/<int:apply_id>/', views.apply_del),
    # 审批开票申请
    path('approve_apply/<int:apply_id>/', views.approve_apply, name='approve_apply'),

    # 开票申请
    path('applyinvoice/', views.applyinvoice, name='apply_inv'),  # 定义开票申请链接

    # 导出数据
    # path('export_pro/', views.export_pro_csv),
    # path('export_inv/', views.export_inv_csv),

    # 暂定为单位自动导入链接
    path('test/', views.test,),
    # 定义手动添加单位链接
    path('unit_list/', views.unit_list, name='unit_list'),
    path('add_unit/', views.add_unit, name='add_unit'),
    path('unit/<int:unit_id>/', views.unit_detail, name='unit_detail'),
    path('del_unit/<int:unit_id>/', views.unit_del),
    # 定义ajax测试链接
    path('ajax/', views.get),
    path('ajax_main/', views.ajax_main),

]

users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views


#  定义用户url
app_name = 'users'

urlpatterns = [
    # 登录与注册
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),

    # 修改密码
    path('password-change/', auth_views.PasswordChangeView.as_view(
                            template_name="account/password_change_form.html",
                            success_url=reverse_lazy('users:password_change_done')), name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(
                                template_name="account/password_change_done.html"), name='password_change_done'),

    path('test/', views.test,),
]

projects/models.py
from django.db import models

from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

# Create your models here.


class SampleType(models.Model):
    #  定义样本类型model

    sampletype = models.CharField(max_length=64, verbose_name="样本类型", unique=True)

    class Meta:
        verbose_name = "样本类型表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sampletype


class ProjectType(models.Model):
    # 定义项目类型model

    projecttype = models.CharField(max_length=64, verbose_name="项目类型", unique=True)
    pro_period = models.PositiveSmallIntegerField(verbose_name="项目周期", null=True, blank=True)
    pre_period = models.PositiveSmallIntegerField(verbose_name="前处理周期", null=True, blank=True)

    class Meta:
        verbose_name = "项目类型表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.projecttype


class CostType(models.Model):
    #  定义收费等级model

    costtype = models.CharField(max_length=64, verbose_name="收费类型", unique=True)

    class Meta:
        verbose_name = "收费类型表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.costtype


class ResPerson(models.Model):
    # 定义实验负责人
    name = models.CharField(max_length=64, verbose_name="负责人", unique=True)

    class Meta:
        verbose_name = "实验负责人"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SupinformationExp(models.Model):
    # 定义实验偏差
    supply_info = models.CharField(max_length=128, verbose_name="实验偏差", unique=True)

    class Meta:
        verbose_name = "实验偏差类型"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.supply_info


class Machine(models.Model):
    # 定义上机仪器
    instrument = models.CharField(max_length=64, verbose_name="上机仪器", unique=True)

    class Meta:
        verbose_name = "仪器类型"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.instrument


class AdditionalCost(models.Model):
    # 定义附加收费类型
    addition_type = models.CharField(max_length=128, verbose_name="附加收费", unique=True)

    class Meta:
        verbose_name = "附加费用类型"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.addition_type


class ProManager(models.Model):
    # 定义项目经理
    pro_manager = models.CharField(max_length=128, verbose_name="项目经理", unique=True)

    class Meta:
        verbose_name = "项目经理列表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.pro_manager


class PayType(models.Model):
    # 定义结算方式
    name = models.CharField(max_length=128, verbose_name="结算方式", unique=True)

    class Meta:
        verbose_name = "结算方式"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class UnitInvoice(models.Model):

    # 定义开票单位
    unit_name = models.CharField(max_length=128, verbose_name="开票单位", unique=True)
    person_add = models.CharField(max_length=128, verbose_name="添加人")
    c_time = models.DateTimeField(verbose_name="添加时间", auto_now_add=True)

    def __str__(self):
        return str(self.unit_name)

    class Meta:
        ordering = ["unit_name"]
        verbose_name = "开票单位"
        verbose_name_plural = verbose_name


# 定义上传文件的目录和名字
def user_directory_path(instance, filename):

    return '{0}/{1}'.format(instance.experiment_num, filename)


class FilesRelated(models.Model):

    # 定义项目相关文件
    file = models.FileField(verbose_name="相关文件", max_length=100, blank=True, null=True)
    c_time = models.DateTimeField(verbose_name="上传时间", auto_now_add=True)

    def __str__(self):

        return str(self.file)

    class Meta:
        verbose_name = "项目相关文件"
        verbose_name_plural = verbose_name


class UrgentWarn(models.Model):
    # 定义加急情况
    warn_type = models.CharField(max_length=128, verbose_name="优先级", unique=True)

    class Meta:
        verbose_name = "优先级"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.warn_type


class ExperimentList(models.Model):
    # 定义项目列表

    experiment_num = models.CharField(max_length=64, verbose_name="项目编号", unique=True)
    pro_type = models.ForeignKey(ProjectType, verbose_name="项目类型", on_delete=models.CASCADE)  # default="蛋白鉴定")
    sam_type = models.ForeignKey(SampleType, verbose_name="样本类型", on_delete=models.CASCADE)
    cost_type = models.ForeignKey(CostType, verbose_name="收费等级", on_delete=models.CASCADE, blank=True, null=True)
    sample_num = models.PositiveSmallIntegerField(verbose_name="样本数量")
    name_terminal = models.CharField(max_length=128, verbose_name="送样终端", blank=True, null=True)
    # unit = models.CharField(max_length=128, verbose_name="送样单位")
    unit = models.ForeignKey(UnitInvoice, verbose_name="送样单位", on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=32, verbose_name="送样人")
    # addition_cost中是否为Foreignkey，还有待商榷
    addition_cost = models.ManyToManyField(AdditionalCost, verbose_name="附加收费", blank=True)  # 新修改
    res_person = models.ForeignKey(ResPerson, verbose_name="步骤一", on_delete=models.CASCADE, blank=True, null=True)
    second_person = models.ForeignKey(ResPerson, verbose_name="步骤二", related_name='pro_second_person', on_delete=models.CASCADE, blank=True, null=True)
    third_person = models.ForeignKey(ResPerson, verbose_name="步骤三", related_name='pro_third_person', on_delete=models.CASCADE, blank=True, null=True)
    fourth_person = models.ForeignKey(ResPerson, verbose_name="步骤四", related_name='pro_fourth_person', on_delete=models.CASCADE, blank=True, null=True)
    date_pre_exp = models.CharField(max_length=64, verbose_name="质控报告发送", blank=True, null=True)
    date_preperation = models.CharField(max_length=32, verbose_name="制备完成", blank=True, null=True)
    supply_info = models.ForeignKey(SupinformationExp, verbose_name="实验偏差", on_delete=models.CASCADE, blank=True,
                                    null=True)
    instrument = models.ForeignKey(Machine, verbose_name="上机仪器", on_delete=models.CASCADE, blank=True, null=True)
    date_test = models.CharField(max_length=64, verbose_name="上机日期", blank=True, null=True)
    date_searchlib = models.CharField(max_length=64, verbose_name="搜库日期", blank=True, null=True)
    date_senddata = models.CharField(max_length=64, verbose_name="数据发送", blank=True, null=True)
    pro_cost = models.PositiveSmallIntegerField(verbose_name="项目金额", blank=True, null=True)
    pro_manager = models.ForeignKey(ProManager, verbose_name="项目经理", on_delete=models.CASCADE, blank=True, null=True)
    pay_mode = models.ForeignKey(PayType, verbose_name="结算方式", on_delete=models.CASCADE, blank=True, null=True)
    deadline_pro = models.CharField(max_length=64, verbose_name="项目截止日期", blank=True, null=True)
    urgent_warn = models.ForeignKey(UrgentWarn, verbose_name="优先级", on_delete=models.CASCADE, blank=True, null=True)
    files = models.ManyToManyField(FilesRelated, verbose_name="相关文件", blank=True)
    c_time = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    def __str__(self):
        return str(self.experiment_num)

    class Meta:
        ordering = ["experiment_num"]
        verbose_name = "项目列表"
        verbose_name_plural = verbose_name


# @receiver(pre_delete, sender=ExperimentList)
# def file_delete(sender, instance, **kwargs):
    # 定义上传文件的删除方法
#    instance.files.delete(False)


class InvoicePayment(models.Model):
    # 定义开票回款表

    contract_num = models.CharField(max_length=128, verbose_name="合同编号")
    num_invoice = models.CharField(max_length=64, verbose_name="发票号", blank=True, null=True, unique=True)
    unit_invoice = models.CharField(max_length=128, verbose_name="开票单位", blank=True, null=True)
    date_invoice = models.CharField(max_length=64, verbose_name="开票日期", blank=True, null=True)
    person_apply = models.CharField(max_length=32, verbose_name="申请人")
    cost_invoice = models.PositiveIntegerField(verbose_name="发票金额", blank=True, null=True)
    date_post = models.CharField(max_length=64, verbose_name="发票寄送日期", blank=True, null=True)
    num_express = models.CharField(max_length=64, verbose_name="发票快递单号", blank=True, null=True)
    date_callback = models.CharField(max_length=64, verbose_name="合同回收日期", blank=True, null=True)
    # void_red = models.NullBooleanField(verbose_name="作废或冲红")
    date_payment = models.CharField(max_length=64, verbose_name="回款日期", blank=True, null=True)
    pro_num = models.ManyToManyField(ExperimentList, verbose_name="项目编号")
    pay_check = models.NullBooleanField(verbose_name="是否结清")
    c_time = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    def __str__(self):
        return str(self.num_invoice)

    class Meta:
        ordering = ["c_time"]
        verbose_name = "开票回款表"
        verbose_name_plural = verbose_name


class RequireInvoice(models.Model):

    # 定义开票要求
    require_content = models.CharField(max_length=128, verbose_name="开票要求")

    def __str__(self):
        return str(self.require_content)

    class Meta:

        verbose_name = "开票要求类型"
        verbose_name_plural = verbose_name


class ReimburseMaterial(models.Model):
    # 定义报账材料
    material_type = models.CharField(max_length=128, verbose_name="报账材料")

    def __str__(self):
        return self.material_type

    class Meta:
        verbose_name = "报账材料类型"
        verbose_name_plural = verbose_name


class TypeApply(models.Model):
    # 定义开票类型
    apply_type = models.CharField(max_length=128, verbose_name="开票类型")

    def __str__(self):

        return str(self.apply_type)

    class Meta:
        verbose_name = "开票类型表"
        verbose_name_plural = verbose_name


class ApplyInvoice(models.Model):

    # 定义开票申请记录模型
    APPLYING = 'AI'
    PASSED = 'PD'
    REFUSED = 'RD'

    status_type = (
        (APPLYING, '申请中'),
        (PASSED, '已通过'),
        (REFUSED, '已拒绝'),
    )
    contract_num = models.CharField(max_length=128, verbose_name="合同编号",)

projects/forms.py
from django import forms
from .models import ExperimentList, InvoicePayment, ApplyInvoice, UnitInvoice
# from django.contrib.admin.widgets import AdminDateWidget


class AddExp(forms.ModelForm):
    # 定义添加项目表单
    date_pre_exp = forms.DateField(label="质控报告发送", widget=forms.DateInput(attrs={'type': 'date'}), required=False)
    date_preperation = forms.DateField(label="制备完成", widget=forms.DateInput(attrs={'type': 'date'}), required=False)
    date_test = forms.DateField(label="上机日期", widget=forms.DateInput(attrs={'type': 'date'}), required=False)
    date_searchlib = forms.DateField(label="搜库日期", widget=forms.DateInput(attrs={'type': 'date'}), required=False)
    date_senddata = forms.DateField(label="数据发送", widget=forms.DateInput(attrs={'type': 'date'}), required=False)
    deadline_pro = forms.DateField(label="项目截止日期", widget=forms.DateInput(attrs={'type': 'date'}), required=False)
    file = forms.FileField(label="相关文件", widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)

    class Meta:
        model = ExperimentList
        fields = ['experiment_num',
                  'pro_type',
                  'sam_type',
                  'cost_type',
                  'sample_num',
                  'name_terminal',
                  'unit',
                  'name',
                  'addition_cost',
                  'res_person',
                  'second_person',
                  'third_person',
                  'fourth_person',
                  'date_pre_exp',
                  'date_preperation',
                  'res_person',
                  'supply_info',
                  'instrument',
                  'date_test',
                  'date_searchlib',
                  'date_senddata',
                  'pro_cost',
                  'pro_manager',
                  'pay_mode',
                  'deadline_pro',
                  'urgent_warn',
                  'files',
                  ]


class AddInvoice(forms.ModelForm):
    # 定义添加开票表单

    date_invoice = forms.DateField(label="开票日期", widget=forms.DateInput(attrs={'type': 'date'}), required=False)
    date_post = forms.DateField(label="发票寄送日期", widget=forms.DateInput(attrs={'type': 'date'}), required=False)
    date_callback = forms.DateField(label="合同回收日期", widget=forms.DateInput(attrs={'type': 'date'}), required=False)
    date_payment = forms.DateField(label="回款日期", widget=forms.DateInput(attrs={'type': 'date'}), required=False)

    class Meta:
        model = InvoicePayment
        fields = ['contract_num',
                  'num_invoice',
                  'unit_invoice',
                  'date_invoice',
                  'person_apply',
                  'cost_invoice',
                  'date_post',
                  'num_express',
                  'date_callback',
                  # 'void_red',
                  'date_payment',
                  'pro_num',
                  'pay_check',
                  ]


class ApplyInvoiceForm(forms.ModelForm):
    # 定义开票申请表单
    # c_time = forms.DateField(label="申请日期", widget=forms.DateInput(attrs={'type': 'date'}),)
    # status = forms.CharField(label="状态", widget=forms.Select())

    class Meta:
        model = ApplyInvoice
        fields = ['contract_num',
                  'unit_name',
                  'new_unit',
                  'duty_paragraph',
                  'bank',
                  'account',
                  'address',
                  'phone',
                  'cost_invoice',
                  'sheet_num',
                  'require_invoice',
                  'contract_file',
                  'list_file',
                  'report_file',
                  'address_linkman',
                  'type_apply',
                  'red_invoice',
                  'note',
                  'pro_num',
                  'person_apply',
                  'status',
                  ]


class UnitForm(forms.ModelForm):
    # 定义客户单位表单
    unit_name = forms.CharField(label="单位名称", widget=forms.TextInput(attrs={'placeholder': '请输入单位全称！'}),)
    # c_time = forms.DateField(label="申请日期", widget=forms.DateInput(attrs={'type': 'date'}),)

    class Meta:
        model = UnitInvoice
        fields = ['unit_name',
                  'person_add',

                  ]

projects/templates/projects/base.html
{% load static %}
{% load notifications_tags %}
{% notifications_unread as unread_count %}

<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %} base {% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- jQuery 3 -->
  <script src="{% static 'adminlte-2.4.10/bower_components/jquery/dist/jquery.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'adminlte-2.4.10/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminlte-2.4.10/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'adminlte-2.4.10/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte-2.4.10/dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect. -->
  <link rel="stylesheet" href="{% static 'adminlte-2.4.10/dist/css/skins/skin-blue.min.css' %}">
  <!--ico图标-->
  <link rel="shortcut icon" href="{% static 'image/favicon.ico' %}" type="image/x-icon" />


  {% block css %}{% endblock %}

</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>LIMS</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>谱度众合</b></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">

          <!-- Messages: style can be found in dropdown.less-->
          <li >
            <a href="{% url 'projects:index' %}"  >
              <i class="fa fa-home"></i>

            </a>

          </li>

          <!-- Notifications Menu -->
          <li class="dropdown notifications-menu">
            <!-- Menu toggle button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              {% if unread_count %}
                  <svg viewBox="0 0 8 8"
                   width="8px"
                   height="8px">
                   <circle cx="4"
                          cy="4"
                          r="4"
                          fill="#ff6b6b"
                          ></circle>
                  </svg>

              {% endif %}
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have {{ unread_count }} notifications</li>
              <li>
                <!-- Inner Menu: contains the notifications -->
                <ul class="menu">
                  {% for notification in request.user.notifications.all %}
                  <li><!-- start notification -->
                    <a href="#">
                      {{ notification }}             <!-- 展示每条消息-->
                    </a>
                  </li>
                  {% empty %}
                  <li>暂无消息</li>
                  {% endfor %}
                  <!-- end notification -->
                </ul>
              </li>
              <li class="footer"><a href="#">View all</a></li>
            </ul>
          </li>

          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              <img src="{% static 'adminlte-2.4.10/dist/img/user2-160x160.jpg' %}" class="user-image" alt="User Image">
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs">{{ request.session.user_name }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <img src="{% static 'adminlte-2.4.10/dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">

                <p>
                  {{ request.session.user_name }}
                  <small>{{ request.session.date_join }}</small> <!--'2019-4-12'-->
                </p>
              </li>

              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="{% url 'users:password_change' %}" class="btn btn-default btn-flat">Settings</a><!--暂时只有密码修改功能-->
                </div>
                <div class="pull-right">
                  <a href="{% url 'users:logout' %}" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{% static 'adminlte-2.4.10/dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ request.session.nickname }}</p>
          <!-- Status -->
          <a href="#"><i class="fa fa-circle text-success"></i>在线</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">导航栏</li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="{% url 'projects:pro_list' %}"><i class="fa fa-dashboard"></i> <span>项目总表</span></a></li>
        <li><a href="{% url 'projects:apply_inv' %}"><i class="fa fa-edit"></i> <span>开票申请</span></a></li>
        <li><a href="{% url 'projects:apply_list' %}"><i class="fa fa-table"></i> <span>开票申请记录</span></a></li>
        <li><a href="{% url 'projects:invoice_list' %}"><i class="fa fa-table"></i> <span>已开发票总表</span></a></li>
        <li><a href="{% url 'projects:unit_list' %}"><i class="fa fa-table"></i> <span>单位列表</span></a></li>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

    {% block breadcrumb %}{% endblock %}

    <!-- Main content -->
    <section class="content container-fluid">

      <!--主题内容放到这里-->
      {% block content %}


      {% endblock content %}

    </section>
    <!-- /.content -->

  </div>
  <!-- /.content-wrapper -->


  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      www.spec-ally.cn
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2020 <a href="http://www.spec-ally.cn" target="_blank">谱度众合生命科技有限公司</a>.</strong> All rights reserved.
  </footer>


</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->


<!-- Bootstrap 3.3.7 -->
<script src="{% static 'adminlte-2.4.10/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlte-2.4.10/dist/js/adminlte.min.js' %}"></script>

{% block script %}{% endblock %}

<script>
    $('ul.sidebar-menu li').each(function(i){
        if($(this).children().first().attr('href')==='{{ request.path }}'){
            $(this).addClass('active');
        }else{
        }
    });
</script>
</body>
</html>

projects/templates/projects/test.html
{% load static %}

<!--{% block content %}-->

<!--{% endblock content %}-->

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<script src="{% static 'jquery-3.3.1.js' %}"></script>
<script>

    {#使用post方式#}
    $(document).ready(function () {
        $('#b').on('click',function () {
        //用AJAX发送数据
        $.ajax({
            //四大参数。。 第一种我们正常提交数据默认发送数据的格式urlencode
            url:'', // 不写默认往当前的地址提交
            type:'post', //传输据的方式
            data:{'l1':$('#l1').val(),'l2':$('#l2').val()},
            {#data:JSON.stringify({'username':'koko','password':'123 '}),  #}
            {#contentType:'application/json', #}
            success:function (data) {

                alert(data);
                $('#d3').val(data);
        },
        })
    })
    });
</script>
</head>
<body>
<form action="">
<input type="text" id="l1">+<input type="text" id="l2">=<input type="text" id="d3">

<button class="btn btn-success" id="b">提交</button>
</form>
</body>
</html>